### PR TITLE
Campaignbase

### PR DESCRIPTION
**Pull request by hunharibo**
A stable-ish campaign base that we can start branching off of. If this makes dev, i would like to bump master as well.

### CODE REVIEW

**Comment by hunharibo** [comment]
You also need a new assetpack for this. I will upload a new file to the drive.

**Comment by Finu** [comment]
Learned something new - thought it won't work like this - but it seems it worked - thnks

**Review by Z3rca — APPROVED** [review]
I am okay with that, worked for me , I have not the time to get into all XMLs. I found in the game Swartzhafen? I think its called "schwartzhafen, check with Jax.

**Review by tristanka — APPROVED** [review]
Looks good 👍

**Pull request merged**
