### PR TITLE
Demo rc2

### PR DESCRIPTION
**Pull request by hunharibo**
Release candidate 2 for the demo which is due in the next few days.

You will need to download new assetpacks for this. 

I am going to write a readme on the drive.

### CODE REVIEW

**Comment by tristanka** [comment]
These changes look amazing overall, great work. Below are a few suggestions. If you dislike or have concerns about any of them, I'd be happy to discuss. I'll be especially likely to concede to coding style preferences.

Also, I only skimmed the XMLs. Not too in-the-know about those.

**Overall**

- I personally dislike having braceless blocks/if statements and think it's worth the space to block it out with braces. Are you opposed to following the style below? It's not a hill I'll die on but I think it's worth discussing.
```
//instead of this
if(x) //do things

//extend it like this?
if(x)
{
  //do things
}
```
- I think usage of `this`, especially in conjunction with the coding convention of underscores before private fields (which denotes an instance variable, same as `this`) is unnecessarily verbose. When referring to private fields, can we remove `this`?
- There are some cases of lost camel casing, like `_movingSoundindex` in FireBallAbilityScript.cs. 

**AbilityComponent.cs**

- Small change for consistency's sake: there's no new-line between the fields and the constructor, while most (or all) other classes have a new line denoting that separation.
- `agent.GetAbilitiesFromXML()` looks like it's reading from an XML, but it's really reading from memory. I'd simplify this to `GetAbilities()`
- Should we log a warning whenever the instance created from the ability type isn't `BaseAbility`? (~Lines 25-27)
- `SelectNextAbility()` performs a search on the current ability name. We can avoid searching the list by keeping track of the current ability index in the component. Then, `SelectNextAbility()`'s implementation would just be one line, `SelectAbility(_currentIndex+1);`. 
- In conjunction with the above change, `SelectAbility(int index)` could be changed to:
```
public void SelectAbility(int index)
{
   if (_knownAbilities.Count > 0)
   {
       _currentAbilityIndex = index % _knownAbilities.Count;
       CurrentAbility = _knownAbilities[_currentAbilityIndex];
   }
}
```


**AbilityHUD_VM.cs**

- The private fields are below the default constructor and UpdateProperties() method - can these be swapped? Most classes have the fields at the top of the class.
- UpdateProperties() references both HasAnyAbility and _hasAnyAbility. I think it'd be more clear if we just stuck to using the property HasAnyAbility instead of the field. By extension, is there any reason we should ever be getting/setting using the _field rather than the property? (e.g. Line 20, `this._ability = Agent.Main.GetCurrentAbility();`)


**AbilityManagerMissionLogic.cs**

- No concerns, but I'd like to note that we may want to have configurable keybinds eventually and the [Command](https://gameprogrammingpatterns.com/command.html) pattern would work well here. **(No need to address this during this pull request, just a note and food for thought)**


**BaseAbility.cs**

- Renaming `_timer_Elapsed()` to `TimerElapsed()` would be more consistent with the rest of the code.
- `GetOnCoolDownStatus()`-> `IsOnCooldown()`? 
- `public void Use(Agent agent)` -> `public void Use(Agent user)`?


**FireBallAbility.cs**

- The `agent.GetMorale() > 1` check on line 27 seems to be intended to prevent fleeing agents from casting spells. If that's correct, can we check for `!agent.IsRetreating()` instead? As it stands, (extremely) crumbling undead would be unable to use fireball.


**FireBallAbilityScript.cs**

- Instead of using an instance of `Random` within the FireBallAbilityScript, add a new `GetRandomInt()` method (or something similarly named) to TOWMath and utilize the existing static Random instance within that utility class. This way, we avoid multiple `Random()`s being created with the same seed (seeded on system clock) and we save memory and LoC on not having to manage `Random` objects in the classes that need RNG.
- The details of `_agent` aren't readily apparent based on the name. Maybe name this `user`, `caster`, or something that reflects that it's the agent that used the ability.
- `_firstCollision` -> `_hasCollided`? Reading `_firstCollision` has me expecting the type to be of some Collision data.


**WindOfDeathAbility.cs**

- Same as FireBallAbility.cs


**WindOfDeathAbilityScript.cs**

- There are a lot of similarities between this script and the FireBall script. They share many fields and some of the OnTick behavior is the same (specifically the abilitylife check and fadeout). Is it possible to create a parent class for these AbilityScripts (ScriptComponentBehavior -> AbilityScriptComponentBehavior -> *AbilityScript) so that we can aggregate these common factors or is there a reason they have to be direct children of ScriptComponentBehavior?
- DamageAgents() seems like it could be a prime candidate for a Battle Utility method. That way, any class that wants to deal damage to agents in an area can call `TOWBattle.DamageAgentsInArea(Vec2 center, float radius)`. Then `DamageAgents()` can simply set the `_timeSinceLastDamage` and then call `TOWBattle.DamageAgentsInArea(Vec2 center, float radius)`. I think this is valuable because (1) we can, at any time, change how we apply AOE damage, and (2) it helps future developers apply AOE damage without having to track down the implementation in some other class (like checking an AOE ability script). Alternatively, if we want to avoid utility classes, we could have a base AOEAbilityScript class that has the AOE damage logic accessible for any child AOE ability.


**XMLAbilityLoader.cs**

- This class both loads and manages ability data - can we name this AbilityManager instead? XMLAbilityLoader seems to indicate that all it does is load the abilities from an XML. `XMLAbilityLoader.GetAbilitiesForCharacter()` looks like it loads the abilities from an XML, but it actually loads them from memory.


**UndeadMoraleAgentComponent.cs**

- TaleWorlds provides an extension method to access `_moraleComponent.Morale` in `Agent.GetMorale()` if we prefer that (may be more readable)
- Not to contest the change, but I'm curious what the value is of using tick delta instead of the TaleWorlds timer. Is the TaleWorlds timer independent from the game time, causing laggy games to have more damage per unit game time?
- Line 47, `Agent.IsRetreating()` confused me: this should always be false for Undead units, right? It looks like `Retreat()` is only ever called on panicking agents, and, as per the TOWBattleMoraleModel, Undead units never panic.


**TOWBattleMoraleModel.cs**

- No suggestions, but want to note that we may be able to implement Expendable in here using the `GetImportance()` method. 
```
 public override float GetImportance(Agent agent)
{
    if(agent.IsExpendable())
    {
        return 0;
    }
    return base.GetImportance(agent);
}
```

**Review by tristanka — CHANGES_REQUESTED** [review]
Feedback here: https://github.com/WarhammerTheOldWorld/TOW_Core/pull/8#issuecomment-827245900

**Comment by hunharibo** [comment]
What an amazing, nicely detailed review. Thank you very much!
Coding style preferences:
* I am not opposed to always breaking out if statements to a code block with curly brackets. I usually only do this when there are multiple lines in the codeblock, and do it inline when there is a single method call only. But I am indifferent, if you think it enchances code readability, i can agree with that.
* Usage of the "this" keyword. It is just a personal preferance of mine for autocomplete / intellisense reasons, but i can live without it.

* AbilityComponent - agree with your suggestions, will change.
* AbilityHUD_VM - agree with your suggestions, will change.
* AbilityManagerMissionLogic - yes for sure, we will want to make the keybinds customizable. We might have to look at McM integration of make our own custom settings solution
* BaseAbility - agree with your suggestions, will change.
* FireBallAbility - agree with your suggestions, will change.
* Scripts - yes, there is a use case for abstracting away a BaseAbilityScript and inheriting Fireball and windOfDeath from that. I did not want to bother with this for the demo. But when we do implement more abilities, this should be a refactor target. 
* AOE damage - will make a utility method as per the suggestion
* XMLAbilityLoader - agree with your suggestions, will change.
* UndeadMoraleAgentComponent - sorry for removing the Timer, there is no value in doing it this way as opposed to how you implemented it. I was debugging the particle effect not showing and left it like this - although this wasnt the reason for the bug.

Retreating in my experience is not the same as routing/fleeing/panicking. There is a tactical retreat option for the AI as well when  for example after charging they retreat to a more favourable position. I am not exactly sure about the inner workings for this yet, but I thought it was safer to keep this condition here. If you can confirm that Retreat is only ever called on panicking agents then this is indeed redundant.

**Comment by hunharibo** [comment]
Pushed the branch with some changes based on Tristan's requests. Pls review again. thx.

**Review by tristanka — APPROVED** [review]
Looks good, approved. 👍

**Comment by Z3rca** [comment]
okay generally I agree with what Tristan is suggesting. (sorry for just jumping on the train :D). I am more of the party of reducing too much paranthesis, but I agree that this can increase readability, especially if our scripts become more complicated. 

My concern is in regard to the code are mostly just high level complaining. I hope that I don't get something wrong, this pull request was huge :D. I think most concerncing the ability scripts are just naming and moving methods. ability is more a picky request, which might be nelectable

### AbilityHUDMissionView.cs 

here you use on the Update method, or OnMissionTick() a UpdateProperties method. Whats the points of setting the name everynow and then? Instead I would use an Event which is propagated to the HUD class. This could be used for a "activateAbilityEvent", "cooldownPassedAndReady" and "SwitchAbility" event. In the  update, or tick, only  the cooldown timer is updated. This is picky, since it just affects the player. If this is really just not worth the effort I can understand it.


### FireBallAbilityScript.cs , WindOfDeathAbilityScript.cs

- I would change the Name ending to Event, or ActionEvent? I don't like scripts called scripts :) 
- apart from this, I would, in future change those to Projectiles, or Vortex as Names, and find for Fireballs and Wind of Death seperate sub Classes? That's more or less thoughts for the future. There will be alot of different Abilities, where many are still working very similar,  and imo, those should be abstracted on this level.
- lights and Physics should be moved to Utility Space if possible,  reducing potential uses of MB2 namespaces. Also not important now, we might have to think about it more. I could imagine, that we get here more options in future.
- Apart from this, the current Hit detection of the fireball  is pretty odd, we should state somewhere that it doesn't work reliable.  

apart from this, I currently didn't found anything.

**Review by Z3rca — APPROVED** [review]

**Pull request merged**
